### ISSUE TITLE
Todo...

### ISSUE THREAD

**Issue by ear1grey** [portsoc/ws_canvas#2]
- [x] Remove all XHR tests
- [ ] Add all XHR (the code is in 5f96d3e89c5804c9872448c552737f5f574f3aa9) to new repo and repurpose for use as Fetch (with an old-skool lookback to XHR and how you will see old programs doing it).
- [x] Add eyes challenge: draw a pair of eyes - a black outlined white circle with a colourful pupil and black iris, x2.  Advanced challenge: make the eyes follow your mouse cursor when it's over the canvas.
- [x] Draw a happy yellow smiley face.  Use the eyes you have already created.  Stretch and scale it to the available canvas as you see fit (but it must be different sizes for different canvases).
- [x] Emoji challenge: draw your favourite emoji using canvas.

**Comment by jacekkopecky** [comment]
question re moving to new repo: do we use ws_ajax?

**Comment by jacekkopecky** [comment]
all done; the second item is now portsoc/ws_ajax#1
